
Application/%.obj: ../Application/%.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_app_FlashROM_StackLibrary.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_stack_library/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Application" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Startup" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/PROFILES" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Include" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/heapmgr" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/sdata" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="Application/$(basename $(<F)).d_raw" --obj_directory="Application" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

PROFILES/%.obj: ../PROFILES/%.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_app_FlashROM_StackLibrary.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_stack_library/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Application" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Startup" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/PROFILES" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Include" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/heapmgr" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/sdata" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="PROFILES/$(basename $(<F)).d_raw" --obj_directory="PROFILES" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

Drivers/ECC/ECCROMCC26XX.obj: $(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/ecc/ECCROMCC26XX.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_app_FlashROM_StackLibrary.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_stack_library/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Application" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Startup" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/PROFILES" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Include" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/heapmgr" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/sdata" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="Drivers/ECC/$(basename $(<F)).d_raw" --obj_directory="Drivers/ECC" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

Drivers/TRNG/TRNGCC26XX.obj: $(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/TRNGCC26XX.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_app_FlashROM_StackLibrary.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_stack_library/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Application" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Startup" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/PROFILES" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Include" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/heapmgr" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/sdata" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="Drivers/TRNG/$(basename $(<F)).d_raw" --obj_directory="Drivers/TRNG" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

Startup/board.obj: $(TI_SDK_PATH)/source/ti/ble5stack/target/board.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_app_FlashROM_StackLibrary.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_stack_library/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Application" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Startup" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/PROFILES" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Include" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/heapmgr" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/sdata" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="Startup/$(basename $(<F)).d_raw" --obj_directory="Startup" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

Startup/%.obj: ../Startup/%.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_app_FlashROM_StackLibrary.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_stack_library/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Application" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Startup" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/PROFILES" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Include" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/heapmgr" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/sdata" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="Startup/$(basename $(<F)).d_raw" --obj_directory="Startup" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

ICallBLE/ble_user_config.obj: $(TI_SDK_PATH)/source/ti/ble5stack/icall/app/ble_user_config.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_app_FlashROM_StackLibrary.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_stack_library/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Application" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Startup" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/PROFILES" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Include" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/heapmgr" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/sdata" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="ICallBLE/$(basename $(<F)).d_raw" --obj_directory="ICallBLE" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

ICallBLE/icall_api_lite.obj: $(TI_SDK_PATH)/source/ti/ble5stack/icall/app/icall_api_lite.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_app_FlashROM_StackLibrary.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_stack_library/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Application" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Startup" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/PROFILES" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Include" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/heapmgr" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/sdata" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="ICallBLE/$(basename $(<F)).d_raw" --obj_directory="ICallBLE" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

ICall/icall.obj: $(TI_SDK_PATH)/source/ti/ble5stack/icall/src/icall.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_app_FlashROM_StackLibrary.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_stack_library/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Application" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Startup" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/PROFILES" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Include" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/heapmgr" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/sdata" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="ICall/$(basename $(<F)).d_raw" --obj_directory="ICall" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

ICall/icall_cc2650.obj: $(TI_SDK_PATH)/source/ti/ble5stack/icall/src/icall_cc2650.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_app_FlashROM_StackLibrary.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_stack_library/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Application" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Startup" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/PROFILES" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Include" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/heapmgr" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/sdata" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="ICall/$(basename $(<F)).d_raw" --obj_directory="ICall" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

ICall/icall_user_config.obj: $(TI_SDK_PATH)/source/ti/ble5stack/icall/src/icall_user_config.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_app_FlashROM_StackLibrary.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_stack_library/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Application" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Startup" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/PROFILES" --include_path="/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Include" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/heapmgr" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/sdata" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="ICall/$(basename $(<F)).d_raw" --obj_directory="ICall" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

build-1103652863:
	@$(MAKE) --no-print-directory -Onone -f TOOLS/subdir_rules.mk build-1103652863-inproc

build-1103652863-inproc: ../TOOLS/app_ble.cfg
	@echo 'Building file: "$<"'
	@echo 'Invoking: XDCtools'
	"$(CCS_PATH)/xdctools_3_62_01_16_core/xs" --xdcpath="$(TI_SDK_PATH)/source;$(TI_SDK_PATH)/kernel/tirtos/packages;$(TI_SDK_PATH)/source/ti/ble5stack;" xdc.tools.configuro -o configPkg -t ti.targets.arm.elf.M3 -p ti.platforms.simplelink:CC2640R2F -r release -c "$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS" --compileOptions "-mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=\"/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app\" --include_path=\"/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Application\" --include_path=\"/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Startup\" --include_path=\"/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/PROFILES\" --include_path=\"/workspace/firmware/ble5_simple_peripheral_cc2640r2lp_app/Include\" --include_path=\"$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc\" --include_path=\"$(TI_SDK_PATH)/source/ti/ble5stack/inc\" --include_path=\"$(TI_SDK_PATH)/source/ti/ble5stack/rom\" --include_path=\"$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx\" --include_path=\"$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc\" --include_path=\"$(TI_SDK_PATH)/source/ti/ble5stack/target\" --include_path=\"$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common\" --include_path=\"$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx\" --include_path=\"$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc\" --include_path=\"$(TI_SDK_PATH)/source/ti/ble5stack/heapmgr\" --include_path=\"$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc\" --include_path=\"$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc\" --include_path=\"$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr\" --include_path=\"$(TI_SDK_PATH)/source/ti/ble5stack/services/src/sdata\" --include_path=\"$(TI_SDK_PATH)/source/ti/devices/cc26x0r2\" --include_path=\"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include\" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi " "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

configPkg/linker.cmd: build-1103652863 ../TOOLS/app_ble.cfg
configPkg/compiler.opt: build-1103652863
configPkg: build-1103652863

