HAL/Common/hal_assert.obj: $(TI_SDK_PATH)/source/ti/ble5stack/hal/src/common/hal_assert.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_stack_library_FlashROM_Library.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=$(STACK_LIBRARY_PATH) --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/npi/src" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/aes/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/rf_patches" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/inc" --include_path="$(TI_SDK_PATH)/source" --include_path="$(TI_SDK_PATH)/kernel/tirtos/packages" --include_path="$(CCS_PATH)/xdctools_3_62_01_16_core/packages" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="HAL/Common/$(basename $(<F)).d_raw" --obj_directory="HAL/Common" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

HAL/Target/CC2650/Drivers/hal_flash_wrapper.obj: $(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/hal_flash_wrapper.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_stack_library_FlashROM_Library.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=$(STACK_LIBRARY_PATH) --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/npi/src" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/aes/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/rf_patches" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/inc" --include_path="$(TI_SDK_PATH)/source" --include_path="$(TI_SDK_PATH)/kernel/tirtos/packages" --include_path="$(CCS_PATH)/xdctools_3_62_01_16_core/packages" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="HAL/Target/CC2650/Drivers/$(basename $(<F)).d_raw" --obj_directory="HAL/Target/CC2650/Drivers" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

HAL/Target/CC2650/Drivers/hal_rtc_wrapper.obj: $(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/hal_rtc_wrapper.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_stack_library_FlashROM_Library.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=$(STACK_LIBRARY_PATH) --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/npi/src" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/aes/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/rf_patches" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/inc" --include_path="$(TI_SDK_PATH)/source" --include_path="$(TI_SDK_PATH)/kernel/tirtos/packages" --include_path="$(CCS_PATH)/xdctools_3_62_01_16_core/packages" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="HAL/Target/CC2650/Drivers/$(basename $(<F)).d_raw" --obj_directory="HAL/Target/CC2650/Drivers" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

HAL/Target/CC2650/Drivers/hal_trng_wrapper.obj: $(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/hal_trng_wrapper.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_stack_library_FlashROM_Library.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=$(STACK_LIBRARY_PATH) --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/npi/src" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/aes/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/rf_patches" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/inc" --include_path="$(TI_SDK_PATH)/source" --include_path="$(TI_SDK_PATH)/kernel/tirtos/packages" --include_path="$(CCS_PATH)/xdctools_3_62_01_16_core/packages" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="HAL/Target/CC2650/Drivers/$(basename $(<F)).d_raw" --obj_directory="HAL/Target/CC2650/Drivers" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

HAL/Target/CC2650/_common/mb_patch.obj: $(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx/mb_patch.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_stack_library_FlashROM_Library.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=$(STACK_LIBRARY_PATH) --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/npi/src" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/aes/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/rf_patches" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/inc" --include_path="$(TI_SDK_PATH)/source" --include_path="$(TI_SDK_PATH)/kernel/tirtos/packages" --include_path="$(CCS_PATH)/xdctools_3_62_01_16_core/packages" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="HAL/Target/CC2650/_common/$(basename $(<F)).d_raw" --obj_directory="HAL/Target/CC2650/_common" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

Host/gatt_uuid.obj: $(TI_SDK_PATH)/source/ti/ble5stack/host/gatt_uuid.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_stack_library_FlashROM_Library.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=$(STACK_LIBRARY_PATH) --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/npi/src" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/aes/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/rf_patches" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/inc" --include_path="$(TI_SDK_PATH)/source" --include_path="$(TI_SDK_PATH)/kernel/tirtos/packages" --include_path="$(CCS_PATH)/xdctools_3_62_01_16_core/packages" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="Host/$(basename $(<F)).d_raw" --obj_directory="Host" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

ICallBLE/ble_dispatch_JT.obj: $(TI_SDK_PATH)/source/ti/ble5stack/icall/stack/ble_dispatch_JT.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_stack_library_FlashROM_Library.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=$(STACK_LIBRARY_PATH) --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/npi/src" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/aes/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/rf_patches" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/inc" --include_path="$(TI_SDK_PATH)/source" --include_path="$(TI_SDK_PATH)/kernel/tirtos/packages" --include_path="$(CCS_PATH)/xdctools_3_62_01_16_core/packages" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="ICallBLE/$(basename $(<F)).d_raw" --obj_directory="ICallBLE" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

ICallBLE/ble_dispatch_lite.obj: $(TI_SDK_PATH)/source/ti/ble5stack/icall/stack/ble_dispatch_lite.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_stack_library_FlashROM_Library.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=$(STACK_LIBRARY_PATH) --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/npi/src" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/aes/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/rf_patches" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/inc" --include_path="$(TI_SDK_PATH)/source" --include_path="$(TI_SDK_PATH)/kernel/tirtos/packages" --include_path="$(CCS_PATH)/xdctools_3_62_01_16_core/packages" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="ICallBLE/$(basename $(<F)).d_raw" --obj_directory="ICallBLE" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

ICallBLE/icall_lite_translation.obj: $(TI_SDK_PATH)/source/ti/ble5stack/icall/src/icall_lite_translation.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_stack_library_FlashROM_Library.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=$(STACK_LIBRARY_PATH) --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/npi/src" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/aes/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/rf_patches" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/inc" --include_path="$(TI_SDK_PATH)/source" --include_path="$(TI_SDK_PATH)/kernel/tirtos/packages" --include_path="$(CCS_PATH)/xdctools_3_62_01_16_core/packages" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="ICallBLE/$(basename $(<F)).d_raw" --obj_directory="ICallBLE" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

NPI/npi.obj: $(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack/npi.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_stack_library_FlashROM_Library.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=$(STACK_LIBRARY_PATH) --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/npi/src" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/aes/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/rf_patches" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/inc" --include_path="$(TI_SDK_PATH)/source" --include_path="$(TI_SDK_PATH)/kernel/tirtos/packages" --include_path="$(CCS_PATH)/xdctools_3_62_01_16_core/packages" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="NPI/$(basename $(<F)).d_raw" --obj_directory="NPI" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

OSAL/osal.obj: $(TI_SDK_PATH)/source/ti/ble5stack/osal/src/common/osal.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_stack_library_FlashROM_Library.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=$(STACK_LIBRARY_PATH) --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/npi/src" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/aes/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/rf_patches" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/inc" --include_path="$(TI_SDK_PATH)/source" --include_path="$(TI_SDK_PATH)/kernel/tirtos/packages" --include_path="$(CCS_PATH)/xdctools_3_62_01_16_core/packages" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="OSAL/$(basename $(<F)).d_raw" --obj_directory="OSAL" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

OSAL/osal_bufmgr.obj: $(TI_SDK_PATH)/source/ti/ble5stack/osal/src/common/osal_bufmgr.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_stack_library_FlashROM_Library.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=$(STACK_LIBRARY_PATH) --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/npi/src" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/aes/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/rf_patches" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/inc" --include_path="$(TI_SDK_PATH)/source" --include_path="$(TI_SDK_PATH)/kernel/tirtos/packages" --include_path="$(CCS_PATH)/xdctools_3_62_01_16_core/packages" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="OSAL/$(basename $(<F)).d_raw" --obj_directory="OSAL" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

OSAL/osal_cbtimer.obj: $(TI_SDK_PATH)/source/ti/ble5stack/osal/src/common/osal_cbtimer.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_stack_library_FlashROM_Library.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=$(STACK_LIBRARY_PATH) --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/npi/src" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/aes/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/rf_patches" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/inc" --include_path="$(TI_SDK_PATH)/source" --include_path="$(TI_SDK_PATH)/kernel/tirtos/packages" --include_path="$(CCS_PATH)/xdctools_3_62_01_16_core/packages" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="OSAL/$(basename $(<F)).d_raw" --obj_directory="OSAL" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

OSAL/osal_clock.obj: $(TI_SDK_PATH)/source/ti/ble5stack/osal/src/common/osal_clock.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_stack_library_FlashROM_Library.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=$(STACK_LIBRARY_PATH) --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/npi/src" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/aes/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/rf_patches" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/inc" --include_path="$(TI_SDK_PATH)/source" --include_path="$(TI_SDK_PATH)/kernel/tirtos/packages" --include_path="$(CCS_PATH)/xdctools_3_62_01_16_core/packages" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="OSAL/$(basename $(<F)).d_raw" --obj_directory="OSAL" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

OSAL/osal_list.obj: $(TI_SDK_PATH)/source/ti/ble5stack/osal/src/common/osal_list.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_stack_library_FlashROM_Library.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=$(STACK_LIBRARY_PATH) --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/npi/src" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/aes/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/rf_patches" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/inc" --include_path="$(TI_SDK_PATH)/source" --include_path="$(TI_SDK_PATH)/kernel/tirtos/packages" --include_path="$(CCS_PATH)/xdctools_3_62_01_16_core/packages" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="OSAL/$(basename $(<F)).d_raw" --obj_directory="OSAL" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

OSAL/osal_memory_icall.obj: $(TI_SDK_PATH)/source/ti/ble5stack/osal/src/common/osal_memory_icall.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_stack_library_FlashROM_Library.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=$(STACK_LIBRARY_PATH) --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/npi/src" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/aes/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/rf_patches" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/inc" --include_path="$(TI_SDK_PATH)/source" --include_path="$(TI_SDK_PATH)/kernel/tirtos/packages" --include_path="$(CCS_PATH)/xdctools_3_62_01_16_core/packages" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="OSAL/$(basename $(<F)).d_raw" --obj_directory="OSAL" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

OSAL/osal_pwrmgr.obj: $(TI_SDK_PATH)/source/ti/ble5stack/osal/src/common/osal_pwrmgr.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_stack_library_FlashROM_Library.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=$(STACK_LIBRARY_PATH) --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/npi/src" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/aes/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/rf_patches" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/inc" --include_path="$(TI_SDK_PATH)/source" --include_path="$(TI_SDK_PATH)/kernel/tirtos/packages" --include_path="$(CCS_PATH)/xdctools_3_62_01_16_core/packages" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="OSAL/$(basename $(<F)).d_raw" --obj_directory="OSAL" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

OSAL/osal_snv_wrapper.obj: $(TI_SDK_PATH)/source/ti/ble5stack/osal/src/mcu/cc26xx/osal_snv_wrapper.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_stack_library_FlashROM_Library.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=$(STACK_LIBRARY_PATH) --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/npi/src" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/aes/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/rf_patches" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/inc" --include_path="$(TI_SDK_PATH)/source" --include_path="$(TI_SDK_PATH)/kernel/tirtos/packages" --include_path="$(CCS_PATH)/xdctools_3_62_01_16_core/packages" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="OSAL/$(basename $(<F)).d_raw" --obj_directory="OSAL" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

OSAL/osal_timers.obj: $(TI_SDK_PATH)/source/ti/ble5stack/osal/src/common/osal_timers.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_stack_library_FlashROM_Library.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=$(STACK_LIBRARY_PATH) --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/npi/src" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/aes/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/rf_patches" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/inc" --include_path="$(TI_SDK_PATH)/source" --include_path="$(TI_SDK_PATH)/kernel/tirtos/packages" --include_path="$(CCS_PATH)/xdctools_3_62_01_16_core/packages" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="OSAL/$(basename $(<F)).d_raw" --obj_directory="OSAL" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

PROFILES/gap.obj: $(TI_SDK_PATH)/source/ti/ble5stack/host/gap.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_stack_library_FlashROM_Library.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=$(STACK_LIBRARY_PATH) --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/npi/src" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/aes/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/rf_patches" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/inc" --include_path="$(TI_SDK_PATH)/source" --include_path="$(TI_SDK_PATH)/kernel/tirtos/packages" --include_path="$(CCS_PATH)/xdctools_3_62_01_16_core/packages" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="PROFILES/$(basename $(<F)).d_raw" --obj_directory="PROFILES" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

PROFILES/gapbondmgr.obj: $(TI_SDK_PATH)/source/ti/ble5stack/host/gapbondmgr.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_stack_library_FlashROM_Library.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=$(STACK_LIBRARY_PATH) --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/npi/src" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/aes/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/rf_patches" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/inc" --include_path="$(TI_SDK_PATH)/source" --include_path="$(TI_SDK_PATH)/kernel/tirtos/packages" --include_path="$(CCS_PATH)/xdctools_3_62_01_16_core/packages" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="PROFILES/$(basename $(<F)).d_raw" --obj_directory="PROFILES" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

PROFILES/gattservapp_util.obj: $(TI_SDK_PATH)/source/ti/ble5stack/host/gattservapp_util.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_stack_library_FlashROM_Library.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=$(STACK_LIBRARY_PATH) --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/npi/src" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/aes/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/rf_patches" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/inc" --include_path="$(TI_SDK_PATH)/source" --include_path="$(TI_SDK_PATH)/kernel/tirtos/packages" --include_path="$(CCS_PATH)/xdctools_3_62_01_16_core/packages" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="PROFILES/$(basename $(<F)).d_raw" --obj_directory="PROFILES" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

PROFILES/sm_ecc.obj: $(TI_SDK_PATH)/source/ti/ble5stack/host/sm_ecc.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_stack_library_FlashROM_Library.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=$(STACK_LIBRARY_PATH) --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/npi/src" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/aes/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/rf_patches" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/inc" --include_path="$(TI_SDK_PATH)/source" --include_path="$(TI_SDK_PATH)/kernel/tirtos/packages" --include_path="$(CCS_PATH)/xdctools_3_62_01_16_core/packages" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="PROFILES/$(basename $(<F)).d_raw" --obj_directory="PROFILES" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

ROM/common_rom_init.obj: $(TI_SDK_PATH)/source/ti/ble5stack/rom/r2/common_rom_init.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_stack_library_FlashROM_Library.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=$(STACK_LIBRARY_PATH) --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/npi/src" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/aes/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/rf_patches" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/inc" --include_path="$(TI_SDK_PATH)/source" --include_path="$(TI_SDK_PATH)/kernel/tirtos/packages" --include_path="$(CCS_PATH)/xdctools_3_62_01_16_core/packages" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="ROM/$(basename $(<F)).d_raw" --obj_directory="ROM" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

ROM/rom_init.obj: $(TI_SDK_PATH)/source/ti/ble5stack/rom/r2/rom_init.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_stack_library_FlashROM_Library.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=$(STACK_LIBRARY_PATH) --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/npi/src" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/aes/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/rf_patches" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/inc" --include_path="$(TI_SDK_PATH)/source" --include_path="$(TI_SDK_PATH)/kernel/tirtos/packages" --include_path="$(CCS_PATH)/xdctools_3_62_01_16_core/packages" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="ROM/$(basename $(<F)).d_raw" --obj_directory="ROM" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

Startup/ble_user_config.obj: $(TI_SDK_PATH)/source/ti/ble5stack/icall/stack/ble_user_config.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_stack_library_FlashROM_Library.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=$(STACK_LIBRARY_PATH) --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/npi/src" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/aes/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/rf_patches" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/inc" --include_path="$(TI_SDK_PATH)/source" --include_path="$(TI_SDK_PATH)/kernel/tirtos/packages" --include_path="$(CCS_PATH)/xdctools_3_62_01_16_core/packages" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="Startup/$(basename $(<F)).d_raw" --obj_directory="Startup" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

Startup/icall_startup.obj: $(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/icall_startup.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_stack_library_FlashROM_Library.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=$(STACK_LIBRARY_PATH) --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/npi/src" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/aes/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/rf_patches" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/inc" --include_path="$(TI_SDK_PATH)/source" --include_path="$(TI_SDK_PATH)/kernel/tirtos/packages" --include_path="$(CCS_PATH)/xdctools_3_62_01_16_core/packages" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="Startup/$(basename $(<F)).d_raw" --obj_directory="Startup" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

Startup/osal_icall_ble.obj: $(TI_SDK_PATH)/examples/rtos/CC2640R2_LAUNCHXL/ble5stack/simple_peripheral/src/stack/osal_icall_ble.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_stack_library_FlashROM_Library.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=$(STACK_LIBRARY_PATH) --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/npi/src" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/aes/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/rf_patches" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/inc" --include_path="$(TI_SDK_PATH)/source" --include_path="$(TI_SDK_PATH)/kernel/tirtos/packages" --include_path="$(CCS_PATH)/xdctools_3_62_01_16_core/packages" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="Startup/$(basename $(<F)).d_raw" --obj_directory="Startup" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

TOOLS/onboard.obj: $(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/onboard.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/defines/ble5_simple_peripheral_cc2640r2lp_stack_library_FlashROM_Library.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/build_components.opt" --cmd_file="$(TI_SDK_PATH)/source/ti/ble5stack/config/factory_config.opt" --cmd_file=$(STACK_LIBRARY_PATH)"/TOOLS/build_config.opt"  -mv7M3 --code_state=16 -me -O4 --opt_for_speed=0 --include_path=$(STACK_LIBRARY_PATH) --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/controller/cc26xx/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/rom" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/common/cc26xx/npi/stack" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target/_common/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/target" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/hal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/icall/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/npi/src" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/osal/src/inc" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/aes/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv/cc26xx" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/nv" --include_path="$(TI_SDK_PATH)/source/ti/ble5stack/services/src/saddr" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/rf_patches" --include_path="$(TI_SDK_PATH)/source/ti/devices/cc26x0r2/inc" --include_path="$(TI_SDK_PATH)/source" --include_path="$(TI_SDK_PATH)/kernel/tirtos/packages" --include_path="$(CCS_PATH)/xdctools_3_62_01_16_core/packages" --include_path="$(CCS_PATH)/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --define=DeviceFamily_CC26X0R2 -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="TOOLS/$(basename $(<F)).d_raw" --obj_directory="TOOLS" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '
